//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActPCBList
    {
        public string RawBarcode { get; set; }
        public int McID { get; set; }
        public int Lane { get; set; }
        public Nullable<int> PositionInLane { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Original { get; set; }
        public string Validated { get; set; }
        public string ItemId { get; set; }
    }
}
