//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCategory
    {
        public int RID { get; set; }
        public int CID { get; set; }
        public string Categoria { get; set; }
        public string View2 { get; set; }
        public string BoardCategory { get; set; }
        public string SITE { get; set; }
        public string Area { get; set; }
    }
}
