//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCategory
    {
        public int RID { get; set; }
        public int CID { get; set; }
        public string Categoria { get; set; }
        public string View2 { get; set; }
        public string BoardCategory { get; set; }
        public string SITE { get; set; }
        public string Area { get; set; }
    }
}
