//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCharge
    {
        public int RECID { get; set; }
        public string DEPT17 { get; set; }
        public string ORDC17 { get; set; }
        public string ITEM17 { get; set; }
        public string CUENTA { get; set; }
        public string VNDR17 { get; set; }
        public string SNAM05 { get; set; }
        public string CURC17 { get; set; }
        public string VATCOD { get; set; }
        public string OQTY17 { get; set; }
        public string OUOM17 { get; set; }
        public string PRIC17 { get; set; }
        public string PRUM17 { get; set; }
        public string FECREQ { get; set; }
        public string Mes { get; set; }
        public Nullable<int> M { get; set; }
        public string DREQ17 { get; set; }
        public string FECVEN { get; set; }
        public string CNVF17 { get; set; }
        public string REFT17 { get; set; }
        public string ORDU17 { get; set; }
        public string RQRC17 { get; set; }
        public string REQN { get; set; }
        public string USER17 { get; set; }
        public string ORDN17 { get; set; }
        public string LINE17 { get; set; }
        public string FECPO { get; set; }
        public string RSTS05_ { get; set; }
    }
}
