//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetCharges_ant
    {
        public int ChgID { get; set; }
        public Nullable<int> BID { get; set; }
        public string Concepto { get; set; }
        public Nullable<double> Cuenta { get; set; }
        public string Vendor { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ReqNum { get; set; }
        public Nullable<System.DateTime> FechaReq { get; set; }
        public string PONum { get; set; }
        public Nullable<System.DateTime> FechaPO { get; set; }
        public string Documents { get; set; }
        public string Mes { get; set; }
        public string Site { get; set; }
        public string Plant { get; set; }
        public string UserID { get; set; }
        public string Comments { get; set; }
        public string Area { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string BoardCategory { get; set; }
        public Nullable<int> MesNumber { get; set; }
    }
}
