//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetCharge
    {
        public int ChgID { get; set; }
        public string CoCd { get; set; }
        public Nullable<double> BID { get; set; }
        public Nullable<double> Cuenta { get; set; }
        public string Category { get; set; }
        public string Costcenter { get; set; }
        public Nullable<double> DocumentNo { get; set; }
        public string DocTyp { get; set; }
        public Nullable<double> Item { get; set; }
        public Nullable<decimal> ValueTCur { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PostDate { get; set; }
        public string TCurr { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string PUM { get; set; }
        public string OffAct { get; set; }
        public string Vendor { get; set; }
        public string UserID { get; set; }
        public string Plant { get; set; }
        public string PONum { get; set; }
        public Nullable<System.DateTime> FechaPO { get; set; }
        public string Concepto { get; set; }
        public string Comments { get; set; }
        public string Rev { get; set; }
        public string Area { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public string BoardCategory { get; set; }
        public Nullable<int> MesNumber { get; set; }
        public string Site { get; set; }
        public string Mes { get; set; }
        public string ReqNum { get; set; }
        public Nullable<System.DateTime> FechaReq { get; set; }
        public string Documents { get; set; }
    }
}
