//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CBSEntities : DbContext
    {
        public CBSEntities()
            : base("name=CBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OEE_Detail_History> OEE_Detail_History { get; set; }
        public virtual DbSet<Lines> Lines { get; set; }
    
        public virtual ObjectResult<Info_Lines_Result> Info_Lines(string buscarPor, string valorBuscar, Nullable<int> action, string orden, Nullable<int> customerID, string userID)
        {
            var buscarPorParameter = buscarPor != null ?
                new ObjectParameter("BuscarPor", buscarPor) :
                new ObjectParameter("BuscarPor", typeof(string));
    
            var valorBuscarParameter = valorBuscar != null ?
                new ObjectParameter("ValorBuscar", valorBuscar) :
                new ObjectParameter("ValorBuscar", typeof(string));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            var ordenParameter = orden != null ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(string));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Info_Lines_Result>("Info_Lines", buscarPorParameter, valorBuscarParameter, actionParameter, ordenParameter, customerIDParameter, userIDParameter);
        }
    }
}
