//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompList
    {
        public string CompID { get; set; }
        public Nullable<int> FeederID { get; set; }
        public string CompName { get; set; }
        public Nullable<System.DateTime> OpenTimeStamp { get; set; }
        public Nullable<int> NumDryLeft { get; set; }
        public Nullable<int> McID { get; set; }
        public Nullable<int> Station { get; set; }
        public Nullable<int> Slot { get; set; }
        public Nullable<int> SubSlot { get; set; }
        public Nullable<int> Used { get; set; }
        public Nullable<int> Errors { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Correction { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CompPrPCB { get; set; }
        public Nullable<System.DateTime> DryTimeStamp { get; set; }
        public Nullable<int> PreparationStatus { get; set; }
        public Nullable<int> LastSeenOnMachine { get; set; }
        public Nullable<int> BookingMcid { get; set; }
        public Nullable<int> BookingStation { get; set; }
        public Nullable<int> BookingSlot { get; set; }
        public Nullable<int> BookingSubslot { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> IdentifierStatus { get; set; }
    }
}
