//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COVID_Acceso
    {
        public int RecordID { get; set; }
        public string EmpID { get; set; }
        public string Nombre { get; set; }
        public string Departamento { get; set; }
        public string Area { get; set; }
        public string Categoria { get; set; }
        public Nullable<byte> Transporte { get; set; }
        public Nullable<byte> Turno { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<byte> Activo { get; set; }
        public Nullable<System.DateTime> PIN1 { get; set; }
        public Nullable<System.DateTime> PIN2 { get; set; }
    }
}
