//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COVID_Acceso
    {
        public int RecordID { get; set; }
        public string EmpID { get; set; }
        public string Nombre { get; set; }
        public string Departamento { get; set; }
        public string Area { get; set; }
        public string Categoria { get; set; }
        public Nullable<byte> Transporte { get; set; }
        public Nullable<byte> Turno { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<byte> Activo { get; set; }
        public Nullable<System.DateTime> PIN1 { get; set; }
        public Nullable<System.DateTime> PIN2 { get; set; }
    }
}
