//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COVID_ES_Employees
    {
        public int RecordID { get; set; }
        public Nullable<double> EmpID { get; set; }
        public string Nombre { get; set; }
        public string APE_MAT { get; set; }
        public string APE_PAT { get; set; }
        public string Departamento { get; set; }
        public string Categoria { get; set; }
        public string COD_Barras { get; set; }
        public string Pass { get; set; }
        public Nullable<short> Rango { get; set; }
    }
}
