//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepID { get; set; }
        public string Department1 { get; set; }
        public Nullable<int> Manager { get; set; }
        public string Lang { get; set; }
        public string Value { get; set; }
        public Nullable<int> APR1_ID { get; set; }
        public Nullable<int> APR2_ID { get; set; }
        public Nullable<int> APR3_ID { get; set; }
    }
}
