//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepID { get; set; }
        public string Department1 { get; set; }
        public Nullable<int> Manager { get; set; }
        public string Lang { get; set; }
        public string Value { get; set; }
        public Nullable<int> APR1_ID { get; set; }
        public Nullable<int> APR2_ID { get; set; }
        public Nullable<int> APR3_ID { get; set; }
    }
}
