//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceTrace
    {
        public int DeviceID { get; set; }
        public int McID { get; set; }
        public int Station { get; set; }
        public Nullable<int> Slot { get; set; }
        public Nullable<int> SubSlot { get; set; }
        public string CompID { get; set; }
        public Nullable<int> BlockNo { get; set; }
        public string Reference { get; set; }
        public Nullable<int> CompType { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
