//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocID { get; set; }
        public string DocumentName { get; set; }
        public string Area { get; set; }
        public string Topic { get; set; }
        public string DocType { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string UserID { get; set; }
    }
}
