//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long EmpID { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string FullName { get; set; }
        public string Depa { get; set; }
        public string EmployeeType { get; set; }
        public string EmployeeBy { get; set; }
        public string Position { get; set; }
        public Nullable<int> Manager { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Remarks { get; set; }
        public string CostCenter { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public string Site { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
    }
}
