//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long EmpID { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string FullName { get; set; }
        public string Depa { get; set; }
        public string EmployeeType { get; set; }
        public string EmployeeBy { get; set; }
        public string Position { get; set; }
        public Nullable<int> Manager { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Remarks { get; set; }
        public string CostCenter { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public string Site { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
    }
}
