//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HW_MODEL
    {
        public int ModelID { get; set; }
        public string Model { get; set; }
        public string CPU { get; set; }
        public string MEM { get; set; }
        public string VENDOR { get; set; }
        public string TYPE { get; set; }
        public string HD { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string Operator { get; set; }
    }
}
