//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HW_MODEL
    {
        public int ModelID { get; set; }
        public string Model { get; set; }
        public string CPU { get; set; }
        public string MEM { get; set; }
        public string VENDOR { get; set; }
        public string TYPE { get; set; }
        public string HD { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string Operator { get; set; }
    }
}
