//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KamishibaiLog
    {
        public int RecordID { get; set; }
        public string KBNUmber { get; set; }
        public string Description { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string SupervisedBy { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string Confirmed { get; set; }
    }
}
