//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KamishibaiLog
    {
        public int RecordID { get; set; }
        public string KBNUmber { get; set; }
        public string Description { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string SupervisedBy { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string Confirmed { get; set; }
    }
}
