//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiosk
    {
        public int KID { get; set; }
        public string LineID { get; set; }
        public string ButtonName { get; set; }
        public Nullable<int> ID { get; set; }
        public string Programa { get; set; }
        public Nullable<int> PasCode { get; set; }
        public string Evento { get; set; }
    }
}
