//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiosk
    {
        public int KID { get; set; }
        public string LineID { get; set; }
        public string ButtonName { get; set; }
        public Nullable<int> ID { get; set; }
        public string Programa { get; set; }
        public Nullable<int> PasCode { get; set; }
        public string Evento { get; set; }
    }
}
