//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiosk_Log
    {
        public int LogID { get; set; }
        public string Evento { get; set; }
        public string Kiosk_Log1 { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
