//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiosk_Log
    {
        public int LogID { get; set; }
        public string Evento { get; set; }
        public string Kiosk_Log1 { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
