//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lines
    {
        public int LineID { get; set; }
        public string LineName { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<short> Active { get; set; }
        public Nullable<int> IPID { get; set; }
        public Nullable<short> PLCActive { get; set; }
        public Nullable<System.DateTime> PLCLastUpdate { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string UserID { get; set; }
        public string Route_number { get; set; }
        public string Nombre_hc { get; set; }
        public string LineType { get; set; }
    }
}
