//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_History
    {
        public int RecordID { get; set; }
        public Nullable<int> Hw_ID { get; set; }
        public string ComputerName { get; set; }
        public string EmpID { get; set; }
        public string Account { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public string Bios { get; set; }
        public string TrueCrypt { get; set; }
        public string Operator { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Location { get; set; }
        public string Column { get; set; }
        public Nullable<bool> Singnature { get; set; }
    }
}
