//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_HW
    {
        public int Hw_ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string SerialNumber { get; set; }
        public string AssetTag { get; set; }
        public string Vendor { get; set; }
        public string Type { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TypeC { get; set; }
        public string Site { get; set; }
        public string PSite { get; set; }
        public string PONum { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> Refresh_EligDate { get; set; }
        public Nullable<System.DateTime> WarrantyDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastModBy { get; set; }
        public string InventoryLabel { get; set; }
    }
}
