//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_SW
    {
        public int SWID { get; set; }
        public string SoftwareName { get; set; }
        public string Vendor { get; set; }
        public string Standard { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> PurchasedLicenses { get; set; }
        public string PurchasedSite { get; set; }
        public string Site { get; set; }
        public string PONum { get; set; }
        public string Comments { get; set; }
        public string SW_Key { get; set; }
        public Nullable<bool> bActivo { get; set; }
    }
}
