//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITDBEntities : DbContext
    {
        public ITDBEntities()
            : base("name=ITDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<HW_MODEL> HW_MODEL { get; set; }
        public virtual DbSet<Master_HW> Master_HW { get; set; }
        public virtual DbSet<Master_SW> Master_SW { get; set; }
        public virtual DbSet<PhoneMaster> PhoneMasters { get; set; }
        public virtual DbSet<COVID_ES_Employees> COVID_ES_Employees { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Project_Tasks> Project_Tasks { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<BCategory> BCategories { get; set; }
        public virtual DbSet<BCharge> BCharges { get; set; }
        public virtual DbSet<Budget> Budgets { get; set; }
        public virtual DbSet<BudgetCharge> BudgetCharges { get; set; }
        public virtual DbSet<BudgetCharges_ant> BudgetCharges_ant { get; set; }
        public virtual DbSet<COVID_Acceso> COVID_Acceso { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Downtime_Causas> Downtime_Causas { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<INV_Budget> INV_Budget { get; set; }
        public virtual DbSet<KamishibaiLog> KamishibaiLogs { get; set; }
        public virtual DbSet<Kiosk> Kiosks { get; set; }
        public virtual DbSet<Kiosk_Log> Kiosk_Log { get; set; }
        public virtual DbSet<LogHistory> LogHistories { get; set; }
        public virtual DbSet<Maquina> Maquinas { get; set; }
        public virtual DbSet<Master_History> Master_History { get; set; }
        public virtual DbSet<Project_Tracking> Project_Tracking { get; set; }
        public virtual DbSet<ShiftLog> ShiftLogs { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SW_Installs> SW_Installs { get; set; }
        public virtual DbSet<Task_Documents> Task_Documents { get; set; }
        public virtual DbSet<Type_Of_Change> Type_Of_Change { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
