//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEE_Detail_History
    {
        public int Recordid { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> PartsOK { get; set; }
        public Nullable<int> PartsNOK { get; set; }
        public Nullable<int> DownTime { get; set; }
        public Nullable<int> UpTime { get; set; }
        public Nullable<double> CycleTime { get; set; }
        public Nullable<int> BTSID { get; set; }
        public Nullable<double> OEE { get; set; }
        public Nullable<double> FTQ { get; set; }
        public Nullable<double> Availability { get; set; }
        public Nullable<double> Performance { get; set; }
        public Nullable<double> Average { get; set; }
        public Nullable<int> TurnoID { get; set; }
        public Nullable<System.DateTime> TimeDate { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
