//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneMaster
    {
        public int LogID { get; set; }
        public Nullable<double> PhoneID { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Stop { get; set; }
        public string Comment { get; set; }
        public Nullable<double> EmpID { get; set; }
        public string AssignedBy { get; set; }
        public string UnassignedBy { get; set; }
        public string Type { get; set; }
    }
}
