//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public double PhoneID { get; set; }
        public string IDNextel { get; set; }
        public string Region { get; set; }
        public string CuentaPadre { get; set; }
        public string Cuenta { get; set; }
        public string SIM { get; set; }
        public string IMEI { get; set; }
        public string Mode { get; set; }
        public string Plan { get; set; }
        public Nullable<decimal> Renta { get; set; }
        public Nullable<int> MinIncluido { get; set; }
        public Nullable<int> Min_Telcel_Telcel { get; set; }
        public Nullable<int> SMS { get; set; }
        public Nullable<int> Datos { get; set; }
        public string Equipo { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<System.DateTime> FecIni { get; set; }
        public Nullable<System.DateTime> FecFin { get; set; }
        public Nullable<int> MonthLeft { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<double> EmpID { get; set; }
        public string Operator { get; set; }
        public string Status { get; set; }
        public string Comentarios { get; set; }
        public string InvNumber { get; set; }
        public string InvNum { get; set; }
        public string Site { get; set; }
        public string Planta { get; set; }
        public Nullable<int> JP { get; set; }
        public Nullable<System.DateTime> DisconnectDate { get; set; }
    }
}
