//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneMaster
    {
        public int LogID { get; set; }
        public Nullable<double> PhoneID { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Stop { get; set; }
        public string Comment { get; set; }
        public Nullable<double> EmpID { get; set; }
        public string AssignedBy { get; set; }
        public string UnassignedBy { get; set; }
        public string Type { get; set; }
    }
}
