//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Tracking
    {
        public int PID { get; set; }
        public string ProNumber { get; set; }
        public string Project_Name { get; set; }
        public string Benefits { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string Op_Statement { get; set; }
        public string Defecto { get; set; }
        public string Goal_Statement { get; set; }
        public string Scope { get; set; }
        public string Depa { get; set; }
        public string Sitio { get; set; }
        public string Phase1 { get; set; }
        public string Phase2 { get; set; }
        public string Phase3 { get; set; }
        public string Phase4 { get; set; }
        public string Sponsor { get; set; }
        public string StakeHolders { get; set; }
        public string S_Factors { get; set; }
        public string Deliverables { get; set; }
        public string ApprovedBy { get; set; }
        public string Project_Leader { get; set; }
        public string Operator { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
