//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Tasks
    {
        public int TaskID { get; set; }
        public string Task { get; set; }
        public Nullable<int> PID { get; set; }
        public string Phase { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public string Responsible { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Valid { get; set; }
        public string Comments { get; set; }
        public string AssignedBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public string RefreshBy { get; set; }
        public string RefreshDate { get; set; }
        public string KBNumber { get; set; }
    }
}
