//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftLog
    {
        public int RecordID { get; set; }
        public string UserID { get; set; }
        public string Site { get; set; }
        public string Plant { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public string Ticket { get; set; }
        public string ProblemType { get; set; }
        public string TypeID { get; set; }
        public string SystemID { get; set; }
        public string ComponentID { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Update { get; set; }
        public string IT_Text { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> DateRef { get; set; }
        public Nullable<System.DateTime> TakeDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Minutes { get; set; }
        public string Paro { get; set; }
        public string Linea { get; set; }
        public string LogonUser { get; set; }
        public string Remote_Host { get; set; }
        public Nullable<int> Manager { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedComments { get; set; }
        public Nullable<int> GralSeq { get; set; }
        public Nullable<int> UserSeq { get; set; }
    }
}
