//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_Installs
    {
        public int SW_ID { get; set; }
        public int SWID { get; set; }
        public string ComputerName { get; set; }
        public string AssetTag { get; set; }
        public string SoftwareName { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> IDate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> EmpID { get; set; }
    }
}
