//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_Installs
    {
        public int SW_ID { get; set; }
        public int SWID { get; set; }
        public string ComputerName { get; set; }
        public string AssetTag { get; set; }
        public string SoftwareName { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> IDate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> EmpID { get; set; }
    }
}
