//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Documents
    {
        public int DocID { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<System.DateTime> UpLDate { get; set; }
        public Nullable<System.DateTime> RefreshDate { get; set; }
        public string UserID { get; set; }
        public string RefreshUserID { get; set; }
    }
}
