//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Documents
    {
        public int DocID { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<System.DateTime> UpLDate { get; set; }
        public Nullable<System.DateTime> RefreshDate { get; set; }
        public string UserID { get; set; }
        public string RefreshUserID { get; set; }
    }
}
