//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int RecordID { get; set; }
        public string UserID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Password { get; set; }
        public string Site { get; set; }
        public string Receive_Email { get; set; }
        public string AccessLevel { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
        public string Email { get; set; }
        public string ChgPass { get; set; }
        public Nullable<int> PassExpire { get; set; }
        public string Depa { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<System.DateTime> MailSent { get; set; }
        public string Color { get; set; }
        public string InitialPage { get; set; }
    }
}
