//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int RecordID { get; set; }
        public string EmpID { get; set; }
        public string Account { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ProcessedBy { get; set; }
        public string Comments { get; set; }
        public string AccessLvl { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> StaffJ { get; set; }
    }
}
