//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int RecordID { get; set; }
        public string EmpID { get; set; }
        public string Account { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ProcessedBy { get; set; }
        public string Comments { get; set; }
        public string AccessLvl { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> StaffJ { get; set; }
    }
}
