//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int RecordID { get; set; }
        public string UserID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Password { get; set; }
        public string Site { get; set; }
        public string Receive_Email { get; set; }
        public string AccessLevel { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
        public string Email { get; set; }
        public string ChgPass { get; set; }
        public Nullable<int> PassExpire { get; set; }
        public string Depa { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<System.DateTime> MailSent { get; set; }
        public string Color { get; set; }
        public string InitialPage { get; set; }
    }
}
