//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public long Id_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string APaterno_Usuario { get; set; }
        public string AMaterno_Usuario { get; set; }
        public string Departamento { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
        public Nullable<short> Rango { get; set; }
    }
}
