//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public string Contact { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Service { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
