//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vManageEntities : DbContext
    {
        public vManageEntities()
            : base("name=vManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<X_Mail> X_Mail { get; set; }
        public virtual DbSet<XDeclarationProgram> XDeclarationProgram { get; set; }
        public virtual DbSet<ActPCBList> ActPCBList { get; set; }
        public virtual DbSet<XOEE_Detail_History> XOEE_Detail_History { get; set; }
        public virtual DbSet<XOEE_Details_Per_Hour> XOEE_Details_Per_Hour { get; set; }
    }
}
