//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XDeclarationProgram
    {
        public int RecordID { get; set; }
        public int McID { get; set; }
        public string Program { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Noblock { get; set; }
        public string NIP { get; set; }
        public string Suffix { get; set; }
        public string PartNumber { get; set; }
        public string Line { get; set; }
        public string Assy_Line { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UserID { get; set; }
        public Nullable<double> CycleTime { get; set; }
        public Nullable<int> PzsHr { get; set; }
        public Nullable<bool> AutoUpdate { get; set; }
        public Nullable<System.DateTime> AutoDate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
