//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOEE_Detail_History
    {
        public int Recordid { get; set; }
        public Nullable<int> PartsOK { get; set; }
        public Nullable<int> PartsNOK { get; set; }
        public Nullable<int> DownTime { get; set; }
        public Nullable<int> UpTime { get; set; }
        public Nullable<int> ProgDowntime { get; set; }
        public Nullable<double> CycleTime { get; set; }
        public Nullable<int> PzsHr { get; set; }
        public Nullable<int> Panel { get; set; }
        public string NIP { get; set; }
        public Nullable<int> BTSID { get; set; }
        public Nullable<int> McID { get; set; }
        public string ProdLine { get; set; }
        public string WorkOrder { get; set; }
        public Nullable<double> OEE { get; set; }
        public Nullable<double> FTQ { get; set; }
        public Nullable<double> Availability { get; set; }
        public Nullable<double> Performance { get; set; }
        public Nullable<double> Average { get; set; }
        public string Program1 { get; set; }
        public string Program2 { get; set; }
        public string Program3 { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public Nullable<int> HR1 { get; set; }
        public Nullable<int> HR2 { get; set; }
        public Nullable<int> HR3 { get; set; }
        public Nullable<int> TurnoID { get; set; }
        public Nullable<System.DateTime> TimeDate { get; set; }
        public Nullable<bool> Sent { get; set; }
    }
}
