//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XOEE_Details_Per_Hour
    {
        public int RecordID { get; set; }
        public Nullable<System.DateTime> TimeDate { get; set; }
        public Nullable<int> Hora { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> TPz { get; set; }
        public Nullable<int> PzOk { get; set; }
        public Nullable<int> PzNok { get; set; }
        public Nullable<int> DownTime { get; set; }
        public Nullable<double> FTQ { get; set; }
        public Nullable<double> Perf { get; set; }
        public Nullable<double> Avail { get; set; }
        public Nullable<double> OEE { get; set; }
        public Nullable<int> TurnoID { get; set; }
        public Nullable<int> McID { get; set; }
        public Nullable<double> CT { get; set; }
        public string Programa { get; set; }
        public string WorkOrder { get; set; }
        public Nullable<bool> Change { get; set; }
    }
}
