//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Mail
    {
        public int RecordID { get; set; }
        public string Referencia { get; set; }
        public string FileName { get; set; }
        public string Descripcion { get; set; }
        public string Maquina { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Planta { get; set; }
        public Nullable<int> CodigoScrap { get; set; }
        public string Operador { get; set; }
        public Nullable<int> Turno { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> TimeDate { get; set; }
        public Nullable<bool> Sent { get; set; }
    }
}
